-- SQLite
INSERT INTO `STUDENTEXAMS` (STUID, EXAMID, SCORE)
VALUES ();

INSERT INTO `STUDENTEXAMS` (STUID, EXAMID, SCORE)
VALUES (20190101,1,85);

INSERT INTO `STUDENTEXAMS` (STUID, EXAMID, SCORE)
VALUES (20190201,4,87);