-- SQLite
INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (1,1,'test');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (2,1,'test2');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (3,2,'test3');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (4,2,'test4');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (5,1,'test5');