-- SQLite
INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (1,1,'E:\Project\test\test');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (2,1,'E:\Project\test\test2');

INSERT INTO `EXAMSDATA` (EXAMID, CLASSNUMBER, FILELOCATION)
VALUES (3,2,'E:\Project\test\test3');

